// Lua part of the Meloni API, run before the game's main.lua.
// Kept as a C string so the device and the desktop runner need no extra build step.
// Only single quotes in the Lua code, and no backslashes.

const char mel_prelude[] =
"local floor, random = math.floor, math.random\n"
"\n"
"-- helpers known from PICO-8\n"
"function flr(x) return floor(x) end\n"
"function ceil(x) return math.ceil(x) end\n"
"function abs(x) return math.abs(x) end\n"
"function min(a, b) return math.min(a, b) end\n"
"function max(a, b) return math.max(a, b) end\n"
"function sgn(x) return x < 0 and -1 or 1 end\n"
"function mid(a, b, c)\n"
"  if a > b then a, b = b, a end\n"
"  return math.max(a, math.min(b, c))\n"
"end\n"
"function rnd(x)\n"
"  if type(x) == 'table' then return x[random(#x)] end\n"
"  return random() * (x or 1)\n"
"end\n"
"function srand(seed) math.randomseed(floor(seed)) end\n"
"\n"
"-- require() loads modules from the game: require('lib.map') reads lib/map.lua\n"
"local loaded = {}\n"
"function require(name)\n"
"  if loaded[name] ~= nil then return loaded[name] end\n"
"  local path = name:gsub('%.', '/') .. '.lua'\n"
"  local src = __readfile(path)\n"
"  if not src then error(string.format('module %q not found (%s)', name, path), 2) end\n"
"  local chunk = assert(load(src, '@' .. path, 't'))\n"
"  local result = chunk(name)\n"
"  if result == nil then result = true end\n"
"  loaded[name] = result\n"
"  return result\n"
"end\n"
"\n"
"-- savedata(t) / loaddata(): one table per game, survives restarts and updates\n"
"local function serialize(v, depth)\n"
"  local t = type(v)\n"
"  if t == 'number' then\n"
"    if math.type(v) == 'integer' then return tostring(v) end\n"
"    return string.format('%.9g', v)\n"
"  elseif t == 'string' then return string.format('%q', v)\n"
"  elseif t == 'boolean' or t == 'nil' then return tostring(v)\n"
"  elseif t == 'table' then\n"
"    if depth > 32 then error('savedata: table nested too deep (cycle?)', 0) end\n"
"    local parts = {}\n"
"    for k, val in pairs(v) do\n"
"      local tk = type(k)\n"
"      if tk ~= 'string' and tk ~= 'number' then error('savedata: keys must be strings or numbers', 0) end\n"
"      parts[#parts + 1] = '[' .. serialize(k, depth + 1) .. ']=' .. serialize(val, depth + 1)\n"
"    end\n"
"    return '{' .. table.concat(parts, ',') .. '}'\n"
"  end\n"
"  error('savedata: cannot save a ' .. t, 0)\n"
"end\n"
"function savedata(t)\n"
"  local ok, text = pcall(serialize, t, 0)\n"
"  if not ok then error(text, 2) end\n"
"  return __savewrite('return ' .. text)\n"
"end\n"
"function loaddata()\n"
"  local text = __saveread()\n"
"  if not text then return nil end\n"
"  local chunk = load(text, '=save', 't', {})\n"
"  if not chunk then return nil end\n"
"  local ok, t = pcall(chunk)\n"
"  if ok then return t end\n"
"  return nil\n"
"end\n"
"\n"
"-- note('A4') -> 440, note('C#5'), note('Eb3')\n"
"local SEMI = {C = -9, D = -7, E = -5, F = -4, G = -2, A = 0, B = 2}\n"
"function note(n)\n"
"  local l, acc, oct = tostring(n):match('^([A-Ga-g])([#b]?)(%-?%d)$')\n"
"  if not l then error(string.format('bad note %q (use e.g. C4, F#3, Bb5)', tostring(n)), 2) end\n"
"  local s = SEMI[l:upper()] + (acc == '#' and 1 or acc == 'b' and -1 or 0) + (tonumber(oct) - 4) * 12\n"
"  return 440 * 2 ^ (s / 12)\n"
"end\n"
"\n"
"-- tune('C4 E4 G4:2 - C5', bpm, wave, vol, loop, ch): notes with lengths in beats, '-' is a rest\n"
"local tunes = {}\n"
"function tune(text, bpm, wave, vol, loop, ch)\n"
"  bpm = bpm or 120\n"
"  ch = ch or 7\n"
"  local events, t = {}, 0\n"
"  for token in tostring(text):gmatch('%S+') do\n"
"    local name, len = token:match('^([^:]+):?([%d%.]*)$')\n"
"    local beats = tonumber(len) or 1\n"
"    local frames = beats * 60 / bpm * 60\n"
"    if name ~= '-' and name ~= 'R' and name ~= 'r' then\n"
"      events[#events + 1] = {at = floor(t + 0.5), freq = note(name), dur = frames / 60 * 0.9}\n"
"    end\n"
"    t = t + frames\n"
"  end\n"
"  tunes[ch] = {events = events, length = floor(t + 0.5), pos = 1, frame = 0,\n"
"               wave = wave or 'square', vol = vol or 0.3, loop = loop}\n"
"end\n"
"function stoptune(ch)\n"
"  if ch then tunes[ch] = nil; stop(ch) return end\n"
"  for c in pairs(tunes) do stop(c) end\n"
"  tunes = {}\n"
"end\n"
"function __tick()\n"
"  for ch, tn in pairs(tunes) do\n"
"    local ev = tn.events[tn.pos]\n"
"    while ev and ev.at <= tn.frame do\n"
"      tone(ev.freq, ev.dur, tn.wave, tn.vol, ch)\n"
"      tn.pos = tn.pos + 1\n"
"      ev = tn.events[tn.pos]\n"
"    end\n"
"    tn.frame = tn.frame + 1\n"
"    if tn.frame >= tn.length then\n"
"      if tn.loop and tn.length > 0 then tn.frame, tn.pos = 0, 1 else tunes[ch] = nil end\n"
"    end\n"
"  end\n"
"end\n";
